import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import { NavigationMenu, TopMenu } from '@/components/layout';
import { Providers } from '@/store/providers';
import { AnimationDynamic } from '@/components/shared/dynamics/AnimationDynamic';
import { NextIntlClientProvider } from 'next-intl';
import { cookies } from 'next/headers';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'dzencode',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const store = await cookies();
  const locale = store.get('locale')?.value || 'ru';

  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <NextIntlClientProvider>
          <Providers>
            <TopMenu locale={locale} />
            <div className="d-flex">
              <NavigationMenu />
              <div className="flex-grow-1 bg-light">
                <div className="container py-3">
                  <AnimationDynamic>{children}</AnimationDynamic>
                </div>
              </div>
            </div>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
