import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import { NavigationMenu, TopMenu } from '@/components/layout';
import { Providers } from '@/store/providers';
import { AnimationDynamic } from '@/components/shared/dynamics/AnimationDynamic';


const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'dzencode',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <Providers>
          <TopMenu />
          <div className="d-flex">
            <NavigationMenu />
            <div className="flex-grow-1 bg-light">
              <div className="container py-3">
                <AnimationDynamic>{children}</AnimationDynamic>
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
